### ISSUE TITLE
Database Schema Design

### ISSUE THREAD

**Issue by Maxwell-Alexius** [Maxwell-Alexius/FunfXEssen#7]

**Comment by Eileen0917** [comment]
People:
 - name
 - preference

Restaurant:
 - name
 - location

**Comment by akiicat** [comment]
User:
 - name

Dislike:
 - user_id
 - category_id

Restaurant:
 - name
 - location

Restaurant_categories:
  - restaurant_id
  - category_id

Category:
 - name

**Comment by akiicat** [comment]
#10
